export const EXPENSE_CATEGORIES = {
    DINING_OUT: 'DiningOut',
    GROCERIES: 'Groceries',
    LIQUOR: 'Liquor',
    OTHER_FOOD_DRINK: 'OtherFoodDrink',

    GAMES: 'Games',
    MOVIES: 'Movies',
    MUSIC: 'Music',
    SPORTS: 'Sports',
    OTHER_ENTERTAINMENT: 'OtherEntertainment',

    ELECTRONICS: 'Electronics',
    FURNITURE: 'Furniture',
    HOUSEHOLD_SUPPLIES: 'HouseholdSupplies',
    MAINTENANCE: 'Maintenance',
    MORTGAGE: 'Mortgage',
    OTHER_HOME: 'OtherHome',
    PETS: 'Pets',
    RENT: 'Rent',
    SERVICES: 'Services',

    CHILDCARE: 'Childcare',
    CLOTHING: 'Clothing',
    EDUCATION: 'Education',
    GIFTS: 'Gifts',
    INSURANCE: 'Insurance',
    MEDICAL_EXPENSES: 'MedicalExpenses',
    OTHER_LIFE: 'OtherLife',
    TAXES: 'Taxes',

    BICYCLE: 'Bicycle',
    BUS_TRAIN: 'BusTrain',
    CAR: 'Car',
    GAS_FUEL: 'GasFuel',
    HOTEL: 'Hotel',
    OTHER_TRANSPORTATION: 'OtherTransportation',
    PARKING: 'Parking',
    PLANE: 'Plane',
    TAXI: 'Taxi',

    GENERAL: 'General',
    CLEANING: 'Cleaning',
    ELECTRICITY: 'Electricity',
    HEAT_GAS: 'HeatGas',
    OTHER_UTILITIES: 'OtherUtilities',
    TRASH: 'Trash',
    TV_PHONE_INTERNET: 'TVPhoneInternet',
    WATER: 'Water',
};
