export const MAP: Record<string, string> = {
    "Dining Out": "dining-out-icon.png",
    "Groceries": "groceries-icon.png",
    "Liquor": "liquor-icon.png",
    "Other Food Drink": "other-food-icon.png",
    "Games": "games-icon.png",
    "Movies": "movies-icon.png",
    "Music": "music-icon.png",
    "Sports": "sports-icon.png",
    "OtherEntertainment": "other-entertainment-icon.png",
    "Electronics": "electronics-icon.png",
    "Furniture": "furniture-icon.png",
    "HouseholdSupplies": "household-supplies-icon.png",
    "Maintenance": "maintenance-icon.png",
    "Mortgage": "mortgage-icon.png",
    "OtherHome": "other-home-icon.png",
    "Pets": "pets-icon.png",
    "Rent": "rent-icon.png",
    "Services": "services-icon.png",
    "Childcare": "childcare-icon.png",
    "Clothing": "clothing-icon.png",
    "Education": "education-icon.png",
    "Gifts": "gifts-icon.png",
    "Insurance": "insurance-icon.png",
    "MedicalExpenses": "medical-expenses-icon.png",
    "OtherLife": "other-life-icon.png",
    "Taxes": "taxes-icon.png",
    "Bicycle": "bicycle-icon.png",
    "BusTrain": "bus-train-icon.png",
    "Car": "car-icon.png",
    "GasFuel": "gas-fuel-icon.png",
    "Hotel": "hotel-icon.png",
    "OtherTransportation": "other-transportation-icon.png",
    "Parking": "parking-icon.png",
    "Plane": "plane-icon.png",
    "Taxi": "taxi-icon.png",
    "General": "general-icon.png",
    "Cleaning": "cleaning-icon.png",
    "Electricity": "electricity-icon.png",
    "HeatGas": "heat-gas-icon.png",
    "OtherUtilities": "other-utilities-icon.png",
    "Trash": "trash-icon.png",
    "TVPhoneInternet": "tv-phone-internet-icon.png",
    "Water": "water-icon.png"
  }